const baseUrl = import.meta.env.BASE_URL;
const treningA = [
  `${baseUrl}exercises/treningA1.png`,
  `${baseUrl}exercises/treningA2.png`,
  `${baseUrl}exercises/treningA3.png`,
  `${baseUrl}exercises/treningA4.png`,
  `${baseUrl}exercises/treningA5.png`,
  `${baseUrl}exercises/treningA6.png`,
  `${baseUrl}exercises/treningA7.png`,
  `${baseUrl}exercises/treningA8.png`,
];
const treningB = [
  `${baseUrl}exercises/b1.jpg`,
  `${baseUrl}exercises/b2.jpg`,
  `${baseUrl}exercises/b3.jpg`,
  `${baseUrl}exercises/b4.jpg`,
  `${baseUrl}exercises/b5.jpg`,
  `${baseUrl}exercises/b6.jpg`,
  `${baseUrl}exercises/b7.jpg`,
];
const treningC = [
  `${baseUrl}exercises/c1.jpg`,
  `${baseUrl}exercises/c2.jpg`,
  `${baseUrl}exercises/c3.png`,
  `${baseUrl}exercises/c4.png`,
  `${baseUrl}exercises/c5.jpg`,
  `${baseUrl}exercises/c6.jpg`,
  `${baseUrl}exercises/c7.jpg`,
];
const resetImages = [
  `${baseUrl}exercises/reset1.png`,
  `${baseUrl}exercises/reset2.png`,
  `${baseUrl}exercises/reset3.png`,
  `${baseUrl}exercises/reset4.png`,
  `${baseUrl}exercises/reset5.png`,
  `${baseUrl}exercises/reset6.png`,
];

export const workouts = [
  {
    id: "A",
    name: "Trening A",
    subtitle: "Hinge + poślad + plecy + core",
    sections: [
      {
        id: "main",
        name: "Część główna",
        exercises: [
          {
            id: "a-1-rdl",
            name: "RDL z hantlami",
            type: "reps",
            repsText: "3 x 10-15",
            image: treningA[0],
            note: "Tempo 3-1-1. Biodra w tył.",
          },
          {
            id: "a-2-bridge",
            name: "Most biodrowy",
            type: "reps",
            repsText: "3 x 10-15",
            image: treningA[1],
            note: "2 s zatrzymania na górze.",
          },
          {
            id: "a-3-split-squat",
            name: "Split squat wspierany",
            type: "reps",
            repsText: "3 x 6-10 / strona",
            image: treningA[2],
            note: "Kolano miękko, stopa tripod.",
          },
          {
            id: "a-4-row",
            name: "Wiosłowanie jednorącz",
            type: "reps",
            repsText: "3 x 12-20 / strona",
            image: treningA[3],
            note: "Pauza 1-2 s u góry.",
          },
          {
            id: "a-5-prone-tw",
            name: "Prone T/W",
            type: "reps",
            repsText: "2 x 8-12",
            image: treningA[4],
            note: "Poduszka pod brzuch, bez przeprostu.",
          },
          {
            id: "a-6-pull-apart",
            name: "Mini-band pull-apart",
            type: "reps",
            repsText: "3 x 15-25",
            image: treningA[5],
            note: "Band na nadgarstkach.",
          },
          {
            id: "a-7-dead-bug",
            name: "Dead bug",
            type: "reps",
            repsText: "3 x 6-10 / strona",
            image: treningA[6],
            note: "Krótka dźwignia.",
          },
          {
            id: "a-8-side-plank",
            name: "Side plank",
            type: "time",
            durationSec: 30,
            image: treningA[7],
            note: "2 x 20-40 s / strona.",
          },
        ],
      },
    ],
  },
  {
    id: "B",
    name: "Trening B",
    subtitle: "Kolano/stopa + stabilizacja + łopatka",
    sections: [
      {
        id: "main",
        name: "Część główna",
        exercises: [
          {
            id: "b-1-step-up",
            name: "Step-up + zejście",
            type: "reps",
            repsText: "3 x 6-10 / strona",
            image: treningB[0],
            note: "Kontrolowane zejście 2-3 s.",
          },
          {
            id: "b-2-band-walk",
            name: "Lateral band walk",
            type: "reps",
            repsText: "2-3 x 10-15 kroków / strona",
            image: treningB[1],
            note: "Band nad kolanami.",
          },
          {
            id: "b-3-balance",
            name: "Balans na jednej nodze",
            type: "time",
            durationSec: 30,
            image: treningB[2],
            note: "3 x 20-30 s / strona.",
          },
          {
            id: "b-4-pushup-plus",
            name: "Push-up plus",
            type: "reps",
            repsText: "3 x 8-15",
            image: treningB[3],
            note: "Wersja przy ścianie lub blacie.",
          },
          {
            id: "b-5-wall-slides",
            name: "Wall slides",
            type: "reps",
            repsText: "2 x 8-12",
            image: treningB[4],
            note: "Żebra nie uciekają w przód.",
          },
          {
            id: "b-6-suitcase-march",
            name: "Suitcase march",
            type: "time",
            durationSec: 40,
            image: treningB[5],
            note: "3 x 30-45 s / strona.",
          },
          {
            id: "b-7-eversion",
            name: "Ewersja stopy mini-band",
            type: "reps",
            repsText: "2 x 15-20 / strona",
            image: treningB[6],
            note: "Mały zakres ruchu.",
          },
        ],
      },
    ],
  },
  {
    id: "C",
    name: "Trening C",
    subtitle: "Wytrzymałość tyłu uda + plecy + core",
    sections: [
      {
        id: "main",
        name: "Część główna",
        exercises: [
          {
            id: "c-1-hamstring-iso",
            name: "Hamstring heel-dig iso",
            type: "time",
            durationSec: 25,
            image: treningC[0],
            note: "5 x 20-30 s / strona.",
          },
          {
            id: "c-2-bridge-march",
            name: "Glute bridge (marsz)",
            type: "reps",
            repsText: "3 x 8-12 łącznie",
            image: treningC[1],
            note: "Bez bujania miednicy.",
          },
          {
            id: "c-3-row",
            name: "Wiosłowanie jednorącz",
            type: "reps",
            repsText: "3 x 12-20 / strona",
            image: treningC[2],
            note: "Pauza 1-2 s u góry.",
          },
          {
            id: "c-4-prone-tw",
            name: "Prone T/W",
            type: "reps",
            repsText: "2 x 8-12",
            image: treningC[3],
            note: "Bez przeprostu w lędźwiach.",
          },
          {
            id: "c-5-pull-apart",
            name: "Mini-band pull-apart",
            type: "reps",
            repsText: "3 x 15-25",
            image: treningC[4],
            note: "Band na nadgarstkach.",
          },
          {
            id: "c-6-dead-bug",
            name: "Dead bug",
            type: "reps",
            repsText: "3 x 6-10 / strona",
            image: treningC[5],
            note: "Bez przeprostu.",
          },
          {
            id: "c-7-step-down",
            name: "Step-down ekscentryczny",
            type: "reps",
            repsText: "2-3 x 4-6 / strona",
            image: treningC[6],
            note: "Od tygodnia 3, zejście 3-4 s.",
          },
        ],
      },
    ],
  },
  {
    id: "RESET",
    name: "RESET",
    subtitle: "Codzienny reset 10-15 min",
    sections: [
      {
        id: "full",
        name: "Reset pełny",
        exercises: [
          {
            id: "r-1-90-90",
            name: "90/90 oddech",
            type: "time",
            durationSec: 150,
            image: resetImages[0],
            note: "3 rundy x 4-6 oddechów.",
          },
          {
            id: "r-2-hinge",
            name: "Hinge do ściany",
            type: "reps",
            repsText: "2 x 10",
            image: resetImages[1],
            note: "Biodra w tył, miękki krok.",
          },
          {
            id: "r-3-soft-knee",
            name: "Soft knee + tripod",
            type: "time",
            durationSec: 120,
            image: resetImages[2],
            note: "3 x 30-45 s.",
          },
          {
            id: "r-4-knee-to-wall",
            name: "Knee-to-wall",
            type: "reps",
            repsText: "2 x 10 / strona",
            image: resetImages[3],
            note: "Pięta nie odrywa się.",
          },
          {
            id: "r-5-eversion",
            name: "Ewersja stopy mini-band",
            type: "reps",
            repsText: "2 x 15-20 / strona",
            image: resetImages[4],
            note: "Mały zakres ruchu.",
          },
          {
            id: "r-6-wall-slides",
            name: "Wall slides",
            type: "reps",
            repsText: "2 x 8-12",
            image: resetImages[5],
            note: "Żebra nie uciekają w przód.",
          },
        ],
      },
    ],
  },
];
